### 과제1. 시계열데이터 문법 익숙해지기

In [1]:
import pandas as pd
import datetime

In [2]:
from google.colab import files
uploaded = files.upload()

Saving crime.csv to crime.csv

In [4]:
crime = pd.read_csv('crime.csv')

#### 1. 시계열 데이터로 데이터 형태 변경하기 **to_datatime()**

In [9]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460911 entries, 0 to 460910
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           460911 non-null  int64
 1   OFFENSE_TYPE_ID      460911 non-null  object
 2   OFFENSE_CATEGORY_ID  460911 non-null  object
 3   REPORTED_DATE        460911 non-null  datetime64[ns]
 4   GEO_LON              457296 non-null  float64
 5   GEO_LAT              457296 non-null  float64
 6   NEIGHBORHOOD_ID      460911 non-null  object
 7   IS_CRIME             460911 non-null  int64
 8   IS_TRAFFIC           460911 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(3)
memory usage: 31.6+ MB

In [10]:
crime['REPORTED_DATE'] = pd.to_datetime(crime['REPORTED_DATE'])

In [11]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460911 entries, 0 to 460910
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           460911 non-null  int64
 1   OFFENSE_TYPE_ID      460911 non-null  object
 2   OFFENSE_CATEGORY_ID  460911 non-null  object
 3   REPORTED_DATE        460911 non-null  datetime64[ns]
 4   GEO_LON              457296 non-null  float64
 5   GEO_LAT              457296 non-null  float64
 6   NEIGHBORHOOD_ID      460911 non-null  object
 7   IS_CRIME             460911 non-null  int64
 8   IS_TRAFFIC           460911 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(3)
memory usage: 31.6+ MB

- REPORTED_DATE 열의 데이터 형태가 object에서 datetime64로 변경된 것을 확인 가능
- 이렇게 데이터 형태를 시계열로 변경한 후 분석을 진행해야 시계열 데이터 분석 자체가 가능함

- 시계열 데이터 컬럼을 인덱스로 지정

In [15]:
crime_dt = crime.set_index('REPORTED_DATE')

### 2. 처음/끝 특정기간 필터링 **first/last**
- 처음/끝 값으로부터 특정 기간만큼의 데이터를 필터링하는 방법
- df.first(기준이 되는 기간)
- df.last(기준이 되는 기간)

- 시계열 데이터 시간별로 정렬

In [20]:
crime_dt_sort = crime_dt.sort_index()

- 첫 4일 데이터 추출

In [21]:
crime_dt_sort.first('4D')

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2012-01-02 00:06:00,414815,aggravated-assault,aggravated-assault,-104.816860,39.796717,montbello,1,0
2012-01-02 00:06:00,47176,violation-of-restraining-order,all-other-crimes,-104.816860,39.796717,montbello,1,0
2012-01-02 00:16:00,75798,traffic-accident-dui-duid,traffic-accident,-104.971851,39.736874,cheesman-park,0,1
2012-01-02 00:47:00,46063,traffic-accident,traffic-accident,-104.951824,39.740168,congress-park,0,1
2012-01-02 01:35:00,435334,aggravated-assault,aggravated-assault,-104.998131,39.749922,union-station,1,0
...,...,...,...,...,...,...,...,...
2012-01-05 22:21:00,59283,theft-of-motor-vehicle,auto-theft,-105.019028,39.693482,ruby-hill,1,0
2012-01-05 22:27:00,56862,criminal-mischief-graffiti,public-disorder,-104.981969,39.739094,capitol-hill,1,0
2012-01-05 22:32:00,185647,traffic-accident-hit-and-run,traffic-accident,-104.969107,39.733848,cheesman-park,0,1
2012-01-05 23:40:00,45595,harassment,public-disorder,-104.962264,39.681313,university,1,0
2012-01-05 23:43:00,366764,theft-of-motor-vehicle,auto-theft,-104.984986,39.775572,globeville,1,0

- 마지막 4일 데이터 추출

In [22]:
crime_dt_sort.last('4D')

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-09-25 06:45:00,457406,traffic-accident,traffic-accident,-104.968468,39.738408,cheesman-park,0,1
2017-09-25 07:03:00,460701,theft-of-motor-vehicle,auto-theft,-105.052059,39.729155,villa-park,1,0
2017-09-25 07:11:00,457418,weapon-fire-into-occ-bldg,aggravated-assault,-105.015258,39.682161,college-view-south-platte,1,0
2017-09-25 07:13:00,456725,traffic-accident,traffic-accident,-104.899907,39.743794,east-colfax,0,1
2017-09-25 07:15:00,458325,burglary-residence-no-force,burglary,-104.968786,39.749039,city-park-west,1,0
...,...,...,...,...,...,...,...,...
2017-09-29 03:58:00,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0
2017-09-29 03:58:00,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017-09-29 04:12:00,454656,traf-other,all-other-crimes,-105.006426,39.783139,sunnyside,1,0
2017-09-29 04:12:00,455301,drug-pcs-other-drug,drug-alcohol,-105.048416,39.726209,villa-park,1,0
2017-09-29 06:16:00,453457,theft-of-motor-vehicle,auto-theft,-104.890269,39.657222,hampden,1,0

- 정렬 후 추출해야 값이 나옴 (정렬하지 않으면 error 발생)

### 3. 특정시간 필터링 **at_time**
- df.at_time(time, axis = None)
- 특정 시간만 추출
- time : 기준이 될 시간
- axis : 기준이 될 축

- 2017년의 11시 54분 데이터만 추출

In [53]:
crime_dt17 = crime_dt.loc['2017'].sort_index()

In [54]:
crime_dt17.at_time('11:54')

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-01-08 11:54:00,345790,traffic-accident-hit-and-run,traffic-accident,-104.978636,39.746851,north-capitol-hill,0,1
2017-01-13 11:54:00,357683,traffic-accident,traffic-accident,-104.915347,39.653086,hampden-south,0,1
2017-01-23 11:54:00,349908,traffic-accident,traffic-accident,-104.985495,39.736776,capitol-hill,0,1
2017-01-24 11:54:00,346740,violation-of-restraining-order,all-other-crimes,-105.004404,39.737897,lincoln-park,1,0
2017-01-30 11:54:00,173837,theft-of-motor-vehicle,auto-theft,-104.953764,39.792361,elyria-swansea,1,0
...,...,...,...,...,...,...,...,...
2017-09-15 11:54:00,456357,theft-items-from-vehicle,theft-from-motor-vehicle,-104.895249,39.697591,windsor,1,0
2017-09-18 11:54:00,453053,criminal-trespassing,all-other-crimes,-104.925468,39.754356,north-park-hill,1,0
2017-09-21 11:54:00,459737,assault-simple,other-crimes-against-persons,-104.968680,39.747575,city-park-west,1,0
2017-09-26 11:54:00,451682,burglary-residence-by-force,burglary,-104.906129,39.735993,montclair,1,0
2017-09-27 11:54:00,455045,assault-simple,other-crimes-against-persons,-104.904273,39.755631,north-park-hill,1,0

### 4. 특정기간 필터링 **between_time**
- df.between_time(start_time, end_time, include_start = True, include_end = True, axis = None)
- start_time : 기준이 될 시작 시간
- end_time : 기준이 될 끝 시간
- include_start : 시작 시간을 포함할지 여부
- include_end : 끝 시간을 포함할지 여부
axis : 기준이 될 축

- 2015년의 1시~4시 데이터만 추출

In [55]:
crime_dt15 = crime_dt.loc['2015'].sort_index()

In [56]:
# 1. 시작, 끝 모두 포함
crime_dt17.between_time('1:00', '4:00')

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-01-01 01:16:00,370737,assault-simple,other-crimes-against-persons,-104.991384,39.753888,five-points,1,0
2017-01-01 01:16:00,370148,weapon-unlawful-discharge-of,all-other-crimes,-104.838218,39.794725,montbello,1,0
2017-01-01 01:20:00,345896,traf-other,all-other-crimes,-104.961459,39.772793,cole,1,0
2017-01-01 01:26:00,354610,drug-methampetamine-possess,drug-alcohol,-104.979024,39.740146,north-capitol-hill,1,0
2017-01-01 01:28:00,376801,weapon-unlawful-discharge-of,all-other-crimes,-104.971229,39.761793,whittier,1,0
...,...,...,...,...,...,...,...,...
2017-09-29 03:23:00,454321,assault-dv,other-crimes-against-persons,-104.981930,39.734174,capitol-hill,1,0
2017-09-29 03:47:00,453014,traffic-accident-dui-duid,traffic-accident,-104.994559,39.735267,civic-center,0,1
2017-09-29 03:54:00,455008,burglary-business-no-force,burglary,-104.987489,39.674562,rosedale,1,0
2017-09-29 03:58:00,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017-09-29 03:58:00,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0

In [57]:
# 2. 시작 포함, 끝 제외
crime_dt17.between_time('1:00', '4:00', include_end = False)

<ipython-input-57-eacf76f89c2c>:2: FutureWarning: `include_start` and `include_end` are deprecated in favour of `inclusive`.
  crime_dt17.between_time('1:00', '4:00', include_end = False)

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-01-01 01:16:00,370737,assault-simple,other-crimes-against-persons,-104.991384,39.753888,five-points,1,0
2017-01-01 01:16:00,370148,weapon-unlawful-discharge-of,all-other-crimes,-104.838218,39.794725,montbello,1,0
2017-01-01 01:20:00,345896,traf-other,all-other-crimes,-104.961459,39.772793,cole,1,0
2017-01-01 01:26:00,354610,drug-methampetamine-possess,drug-alcohol,-104.979024,39.740146,north-capitol-hill,1,0
2017-01-01 01:28:00,376801,weapon-unlawful-discharge-of,all-other-crimes,-104.971229,39.761793,whittier,1,0
...,...,...,...,...,...,...,...,...
2017-09-29 03:23:00,454321,assault-dv,other-crimes-against-persons,-104.981930,39.734174,capitol-hill,1,0
2017-09-29 03:47:00,453014,traffic-accident-dui-duid,traffic-accident,-104.994559,39.735267,civic-center,0,1
2017-09-29 03:54:00,455008,burglary-business-no-force,burglary,-104.987489,39.674562,rosedale,1,0
2017-09-29 03:58:00,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017-09-29 03:58:00,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0

In [58]:
# 3. 시작 제외, 끝 포함
crime_dt17.between_time('1:00', '4:00', include_start = False)

<ipython-input-58-55783c16da93>:2: FutureWarning: `include_start` and `include_end` are deprecated in favour of `inclusive`.
  crime_dt17.between_time('1:00', '4:00', include_start = False)

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-01-01 01:16:00,370737,assault-simple,other-crimes-against-persons,-104.991384,39.753888,five-points,1,0
2017-01-01 01:16:00,370148,weapon-unlawful-discharge-of,all-other-crimes,-104.838218,39.794725,montbello,1,0
2017-01-01 01:20:00,345896,traf-other,all-other-crimes,-104.961459,39.772793,cole,1,0
2017-01-01 01:26:00,354610,drug-methampetamine-possess,drug-alcohol,-104.979024,39.740146,north-capitol-hill,1,0
2017-01-01 01:28:00,376801,weapon-unlawful-discharge-of,all-other-crimes,-104.971229,39.761793,whittier,1,0
...,...,...,...,...,...,...,...,...
2017-09-29 03:23:00,454321,assault-dv,other-crimes-against-persons,-104.981930,39.734174,capitol-hill,1,0
2017-09-29 03:47:00,453014,traffic-accident-dui-duid,traffic-accident,-104.994559,39.735267,civic-center,0,1
2017-09-29 03:54:00,455008,burglary-business-no-force,burglary,-104.987489,39.674562,rosedale,1,0
2017-09-29 03:58:00,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017-09-29 03:58:00,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0

In [59]:
# 4. 시작, 끝 모두 제외
crime_dt17.between_time('1:00', '4:00', include_start = False, include_end = False)

<ipython-input-59-f2d8586b45ac>:2: FutureWarning: `include_start` and `include_end` are deprecated in favour of `inclusive`.
  crime_dt17.between_time('1:00', '4:00', include_start = False, include_end = False)

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-01-01 01:16:00,370737,assault-simple,other-crimes-against-persons,-104.991384,39.753888,five-points,1,0
2017-01-01 01:16:00,370148,weapon-unlawful-discharge-of,all-other-crimes,-104.838218,39.794725,montbello,1,0
2017-01-01 01:20:00,345896,traf-other,all-other-crimes,-104.961459,39.772793,cole,1,0
2017-01-01 01:26:00,354610,drug-methampetamine-possess,drug-alcohol,-104.979024,39.740146,north-capitol-hill,1,0
2017-01-01 01:28:00,376801,weapon-unlawful-discharge-of,all-other-crimes,-104.971229,39.761793,whittier,1,0
...,...,...,...,...,...,...,...,...
2017-09-29 03:23:00,454321,assault-dv,other-crimes-against-persons,-104.981930,39.734174,capitol-hill,1,0
2017-09-29 03:47:00,453014,traffic-accident-dui-duid,traffic-accident,-104.994559,39.735267,civic-center,0,1
2017-09-29 03:54:00,455008,burglary-business-no-force,burglary,-104.987489,39.674562,rosedale,1,0
2017-09-29 03:58:00,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017-09-29 03:58:00,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0

- 조건 설정에 따라 행 수가 달라지는 것 확인가능

### 5. 데이터나 인덱스를 원하는 기간만큼 쉬프트해주기 **shift**
- df.shift(periods = 1, freq = None, axis = 0, fill_value = NoDefault.no_default)
- periods : 이동할 기간
- freq : 입력 할 경우 인덱스가 이동  
Y, M, D, H, T, S 나 Timestamp, 'Infer'등 가능
- fill_value : shift로 인해 생긴 결측치 대체하는 값

In [37]:
crime_dt_sort.shift(periods = 5, freq = 'Y')

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2016-12-31 00:06:00,414815,aggravated-assault,aggravated-assault,-104.816860,39.796717,montbello,1,0
2016-12-31 00:06:00,47176,violation-of-restraining-order,all-other-crimes,-104.816860,39.796717,montbello,1,0
2016-12-31 00:16:00,75798,traffic-accident-dui-duid,traffic-accident,-104.971851,39.736874,cheesman-park,0,1
2016-12-31 00:47:00,46063,traffic-accident,traffic-accident,-104.951824,39.740168,congress-park,0,1
2016-12-31 01:35:00,435334,aggravated-assault,aggravated-assault,-104.998131,39.749922,union-station,1,0
...,...,...,...,...,...,...,...,...
2021-12-31 03:58:00,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0
2021-12-31 03:58:00,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2021-12-31 04:12:00,454656,traf-other,all-other-crimes,-105.006426,39.783139,sunnyside,1,0
2021-12-31 04:12:00,455301,drug-pcs-other-drug,drug-alcohol,-105.048416,39.726209,villa-park,1,0
2021-12-31 06:16:00,453457,theft-of-motor-vehicle,auto-theft,-104.890269,39.657222,hampden,1,0

- 년 기준 5기간 이동. 즉, 5일 이동

### 6. period로 변환 **to_period**
- df.to_period(freq = None, axis = 0, copy = True)
- freq : 원하는 시간 단위로 변환
- axis : 변환 할 기준 축
- copy : 사본을 형성할지 여부

- 원하는 시간 간격으로 출력

In [38]:
# 년 기준
crime_dt_sort.to_period("Y")

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2012,414815,aggravated-assault,aggravated-assault,-104.816860,39.796717,montbello,1,0
2012,47176,violation-of-restraining-order,all-other-crimes,-104.816860,39.796717,montbello,1,0
2012,75798,traffic-accident-dui-duid,traffic-accident,-104.971851,39.736874,cheesman-park,0,1
2012,46063,traffic-accident,traffic-accident,-104.951824,39.740168,congress-park,0,1
2012,435334,aggravated-assault,aggravated-assault,-104.998131,39.749922,union-station,1,0
...,...,...,...,...,...,...,...,...
2017,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0
2017,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017,454656,traf-other,all-other-crimes,-105.006426,39.783139,sunnyside,1,0
2017,455301,drug-pcs-other-drug,drug-alcohol,-105.048416,39.726209,villa-park,1,0
2017,453457,theft-of-motor-vehicle,auto-theft,-104.890269,39.657222,hampden,1,0

In [39]:
# 월 기준
crime_dt_sort.to_period("M")

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2012-01,414815,aggravated-assault,aggravated-assault,-104.816860,39.796717,montbello,1,0
2012-01,47176,violation-of-restraining-order,all-other-crimes,-104.816860,39.796717,montbello,1,0
2012-01,75798,traffic-accident-dui-duid,traffic-accident,-104.971851,39.736874,cheesman-park,0,1
2012-01,46063,traffic-accident,traffic-accident,-104.951824,39.740168,congress-park,0,1
2012-01,435334,aggravated-assault,aggravated-assault,-104.998131,39.749922,union-station,1,0
...,...,...,...,...,...,...,...,...
2017-09,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0
2017-09,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017-09,454656,traf-other,all-other-crimes,-105.006426,39.783139,sunnyside,1,0
2017-09,455301,drug-pcs-other-drug,drug-alcohol,-105.048416,39.726209,villa-park,1,0
2017-09,453457,theft-of-motor-vehicle,auto-theft,-104.890269,39.657222,hampden,1,0

In [40]:
# 주 기준
crime_dt_sort.to_period("W")

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2012-01-02/2012-01-08,414815,aggravated-assault,aggravated-assault,-104.816860,39.796717,montbello,1,0
2012-01-02/2012-01-08,47176,violation-of-restraining-order,all-other-crimes,-104.816860,39.796717,montbello,1,0
2012-01-02/2012-01-08,75798,traffic-accident-dui-duid,traffic-accident,-104.971851,39.736874,cheesman-park,0,1
2012-01-02/2012-01-08,46063,traffic-accident,traffic-accident,-104.951824,39.740168,congress-park,0,1
2012-01-02/2012-01-08,435334,aggravated-assault,aggravated-assault,-104.998131,39.749922,union-station,1,0
...,...,...,...,...,...,...,...,...
2017-09-25/2017-10-01,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0
2017-09-25/2017-10-01,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017-09-25/2017-10-01,454656,traf-other,all-other-crimes,-105.006426,39.783139,sunnyside,1,0
2017-09-25/2017-10-01,455301,drug-pcs-other-drug,drug-alcohol,-105.048416,39.726209,villa-park,1,0
2017-09-25/2017-10-01,453457,theft-of-motor-vehicle,auto-theft,-104.890269,39.657222,hampden,1,0

### 참고 자료 : https://wikidocs.net/159717